### ISSUE TITLE
Winning move leads to TIE at the last turn

### ISSUE THREAD

**Issue by furkansimsekli** [edtaskin/odin-tic-tac-toe#1]
Cool UI Emre!

I just played couple of times and *accidentally* found out when I played the winning move at the last turn, game results in tie. I'm not sure if this is the rule, but I think it shouldn't be :smile: I can't stand tying with dummy computer :P

![image](https://github.com/edtaskin/odin-tic-tac-toe/assets/51515287/6dd18f12-2467-420c-8c55-5fc0a8ac08f3)

Here, I played (1,0) as last move.

**Comment by edtaskin** [comment]
Hey Furkan, great catch as always :) I had found some other bugs but decided to leave them as they're, since this is an unimportant project, but this one is game-breaking, so I had a look into it and solved a couple of other bugs along the way. It seems to be working correctly now.

**Comment by furkansimsekli** [comment]
Tested and working properly now!
